apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinador
  labels:
    app: coordinador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinador
  template:
    metadata:
      labels:
        app: coordinador
    spec:
      containers:
        - name: coordinador
          image: lucasrueda/coordinador
          ports:
            - containerPort: 5000
          resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"    

---
apiVersion: v1
kind: Service
metadata:
  name: coordinador
spec:
  ports:
    - port: 5000
  selector:
    app: coordinador
  type: LoadBalancer